### ISSUE TITLE
How is ruby-satisfaction tested?

### ISSUE THREAD

**Issue by gma** [nullstyle/ruby-satisfaction#1]
I'm not filing this ticket to be annoying and point out that there are no recent tests in the spec directory, as I'm sure you already know that. Nor am I a fan of the Ruby community's knee jerk over-reaction to testing by testing every last character they type.

However, I seem to be getting fairly broken behaviour from my topic objects (I ask for a topic's replies and I get more topics back - from a different product - instead), and I've nowhere useful to start from other than reading code and stepping through it with the debugger. The problem with that approach is that it'd be quicker for me to write my app with curl and sed...

How is it normally tested? If I could pull up a test suite of sorts I might be able to narrow the problem down fairly quickly. Otherwise I'll just roll my own code to suit my needs.

Cheers,
Graham

**Comment by nullstyle** [comment]
I'm no longer developing this library. Feel free to fork and fix as you like, but if you feel like curl and sed will make things easier for you, than by all means go ahead.  I would recommend that approach.

I'm happy to accept patches, but for all intents, this project is abandoned by me.

-Scott

**Comment by gma** [comment]
Okay - thanks a lot for the super quick reply. I noticed pius has been updating the version on another branch so I'll get in touch with them.

Cheers,
Graham
